#!/usr/bin/env python3
"""
Generate a Liljencrants-Fant (LF) glottal pulse waveform table.

The LF model produces an asymmetric pulse: fast opening, slow closing,
with a return phase. This replaces SAM's symmetric sine table for more
realistic voicing.

Output: C array (256 bytes, 4-bit quantized like the original sinus table)
and Python bytes literal for tables.py.

The table is in the same format as SAM's sinus[256]:
  - Values are 4-bit quantized: high nibble only (0x00..0x70 positive, 0x90..0xF0 negative)
  - Index 0..127 = positive half, 128..255 = negative half
"""

import math
import sys


def generate_lf_pulse(n=256):
    """Generate a Liljencrants-Fant glottal pulse waveform.

    Returns a list of n float values in [-1.0, 1.0].

    Phase breakdown (of 256 samples):
      0-40%   (0-102):   Fast sine-like rise (opening phase)
      40%     (102):      Peak
      40-90%  (102-230):  Gradual exponential decay (closing phase)
      90-100% (230-256):  Quick return to zero (return phase)
    """
    samples = [0.0] * n
    peak_idx = int(n * 0.40)       # 102
    decay_end = int(n * 0.90)      # 230
    # Phase 1: Rising (0 to peak) - sine-like fast rise
    for i in range(peak_idx):
        t = i / peak_idx  # 0..1
        samples[i] = math.sin(t * math.pi / 2.0)  # quarter sine: 0 -> 1

    # Phase 2: Exponential decay (peak to decay_end)
    decay_len = decay_end - peak_idx
    for i in range(decay_len):
        t = i / decay_len  # 0..1
        samples[peak_idx + i] = math.exp(-3.0 * t)  # exponential decay

    # Phase 3: Return phase (decay_end to end) - quick dip negative and back
    return_len = n - decay_end
    for i in range(return_len):
        t = i / return_len  # 0..1
        # Negative dip: -sin curve
        samples[decay_end + i] = -0.4 * math.sin(t * math.pi)

    return samples


def quantize_to_sam_format(samples):
    """Quantize float samples to SAM's 4-bit nibble format.

    SAM uses:
      Positive: 0x00, 0x10, 0x20, 0x30, 0x40, 0x50, 0x60, 0x70
      Negative: 0x90, 0xA0, 0xB0, 0xC0, 0xD0, 0xE0, 0xF0
      (0x80 is unused / zero crossing)

    Maps [-1.0, 1.0] -> [0x90, 0x70] with 0x00 as center.
    """
    result = []
    for s in samples:
        # Clamp
        s = max(-1.0, min(1.0, s))
        if s >= 0:
            # 0.0 -> 0x00, 1.0 -> 0x70
            nibble = int(round(s * 7))
            nibble = max(0, min(7, nibble))
            result.append(nibble << 4)
        else:
            # -0.14 -> 0xF0, -1.0 -> 0x90
            nibble = int(round(-s * 7))
            nibble = max(1, min(7, nibble))
            result.append((16 - nibble) << 4)  # 0xF0..0x90
    return result


def format_c_array(name, data, per_line=16):
    """Format as a C static const uint8_t array."""
    lines = [f'static const uint8_t {name}[{len(data)}] = {{']
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        hex_vals = ','.join(f'0x{v:02x}' for v in chunk)
        lines.append(f'    {hex_vals},')
    lines.append('};')
    return '\n'.join(lines)


def format_python_bytes(data, per_line=16):
    """Format as a Python bytes literal."""
    lines = ['bytes([']
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        hex_vals = ','.join(f'0x{v:02x}' for v in chunk)
        lines.append(f'    {hex_vals},')
    lines.append('])')
    return '\n'.join(lines)


def main():
    samples = generate_lf_pulse(256)
    quantized = quantize_to_sam_format(samples)

    print("/* Liljencrants-Fant glottal pulse table (256 bytes) */")
    print("/* Generated by gen_glottal.py */")
    print("/* Asymmetric: fast opening, slow closing, return phase */")
    print()
    print(format_c_array('glottal_lf', quantized))
    print()
    print("/* Python bytes for tables.py: */")
    print(f"# GLOTTAL_LF = {format_python_bytes(quantized)}")
    print()

    # Verify properties
    peak_val = max(quantized[:128])
    neg_val = min(quantized[128:]) if any(v > 0x80 for v in quantized) else 0
    print(f"# Peak positive: 0x{peak_val:02x}, deepest negative: 0x{neg_val:02x}" if neg_val else f"# Peak positive: 0x{peak_val:02x}")
    print(f"# Total bytes: {len(quantized)}")

    # Optionally write just the C array to stdout for piping
    if '--c-only' in sys.argv:
        print(format_c_array('glottal_lf', quantized))


if __name__ == '__main__':
    main()
